name: PR Title Validator

on:

  pull_request:

    types: [opened, edited, synchronize, reopened]

jobs:

  validate-title:

    runs-on: ubuntu-latest

    steps:

      - name: Check PR title for Jira ID

        uses: actions/github-script@v7

        with:

          script: |

            const prTitle = context.payload.pull_request.title;

            const regex = /\b(SPLUS|ECE)-\d+\b/;

            if (!regex.test(prTitle)) {

              core.setFailed(`❌ PR title "${prTitle}" does not contain a valid Jira ID (SPLUS-xxx or ECE-xxx). Please update it.`);

            } else {

              console.log(`✅ PR title "${prTitle}" contains a valid Jira ID.`);

            }
 
